### ISSUE TITLE
a copy of php-mysqli-database which base on swoole coroutine mysql client

### ISSUE THREAD

**Issue by kiss291323003** [ThingEngineer/PHP-MySQLi-Database-Class#776] opened 2018-07-23 05:09 UTC
I am a Chinese developer，which a fans of PHP-MySQLi-Database-Class，I had a achieve a copy of PHP-MySQLi-Database-Class which is base on swoole coroutine mysql client,could you please help me check it if there is any bugs ?, thank you。
https://github.com/easy-swoole/mysqli

**Comment by avbdr** [comment] 2018-10-11 02:29
closing as not a bug

**Closed by avbdr** 2018-10-11 02:29 UTC
